# **Homework 1 Deep learning**

This file is for the homework of 6289 deep learning. In this file, we implement the Pytorch tutorial and try some code on our own.

# Basic Python
Since I am still quite new to Python, we will start from some basic concepts such as tuple, list, loop etc. Here we can see list is changalbe while tuple is not. Then some examples of function and logic operation are showed. Fibonacci function would be a nice example.

In [7]:
a=[1,2,3]
b=(1,2,3)
a[1]=1
a

def Fibonacci(n):
    if n<=0:
        print("Positive Integer Plz")
    elif n==1:
        return 0
    elif n==2:
        return 1
    else:
        return Fibonacci(n-1)+Fibonacci(n-2)
 
print(Fibonacci(10))

!pip install matplotlib

34


# PyTorch and Matrix

Import the torch first, then we can creat tensors from  Python lists. torch.dim and torch.shape could give the rank and dimension of the tensors. You can also force a datatype for a tensor using parameter dtype. 

Here are some some useful function to generate special matrixs, eye for identity matrix, zeors for zero matrix, ones for 1 matrixs, rand for random matrixs.

Indexes here could be used to select certain row, column or subpart of the matrix. We can also creat an empty tensor. The indexing here is inexclusive.

In [2]:
import torch
print(torch.__version__)


a = torch.tensor([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a)
print('type(a): ', type(a))
print('rank of a: ', a.dim())
print('a.shape: ', a.shape)

emptym = torch.tensor([])
zerom = torch.zeros(3, 3)
onem = torch.ones(3, 3)
idenm = torch.eye(3)
randm = torch.rand(3, 3)
print(emptym)
print(zerom)
print(onem)
print(idenm)
print(randm)

print('Original tensor:')
print(a)
print('shape: ', a.shape)

# Get row 1, and all columns. 
print('\nSingle row:')
print(a[1, :])
print(a[1])  # Gives the same result; we can omit : for trailing dimensions
print('shape: ', a[1].shape)

print('\nSingle column:')
print(a[:, 1])
print('shape: ', a[:, 1].shape)

# Get the first two rows and the last three columns
print('\nFirst two rows, last two columns:')
print(a[:2, -3:])
print('shape: ', a[:2, -3:].shape)

# Get every other row, and columns at index 1 and 2
print('\nEvery other row, middle columns:')
print(a[::2, 1:3])
print('shape: ', a[::2, 1:3].shape)


1.6.0+cu101
tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])
type(a):  <class 'torch.Tensor'>
rank of a:  2
a.shape:  torch.Size([3, 4])
tensor([])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
tensor([[0.6329, 0.6266, 0.6940],
        [0.0869, 0.3755, 0.4374],
        [0.7401, 0.6807, 0.6011]])
Original tensor:
tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])
shape:  torch.Size([3, 4])

Single row:
tensor([5, 6, 7, 8])
tensor([5, 6, 7, 8])
shape:  torch.Size([4])

Single column:
tensor([ 2,  6, 10])
shape:  torch.Size([3])

First two rows, last two columns:
tensor([[2, 3, 4],
        [6, 7, 8]])
shape:  torch.Size([2, 3])

Every other row, middle columns:
tensor([[ 2,  3],
        [10, 11]])
shape:  torch.Size([2, 2])


One thing that should be noted is the .clone(). Assigning value to certain part of a tensor is assigning to the original tensor. So .clone() is useful in creating a new tensor.

In [ ]:
a = torch.tensor([[1, 2, 3, 4], [5, 6, 7, 8]])
b = a[0, 1:]
c = a[0, 1:].clone()
print('Before mutating:')
print(a)
print(b)
print(c)

a[0, 1] = 20  # a[0, 1] and b[0] point to the same element
b[1] = 30     # b[1] and a[0, 2] point to the same element
c[2] = 40     # c is a clone, so it has its own data
print('\nAfter mutating:')
print(a)
print(b)
print(c)

Then we focus on the matrix calculation. First is the elementwise calculation. For 2 tensors, the normal calculation is all elementwise. 

In [ ]:
x = torch.tensor([[1, 2, 3, 4]])
y = torch.tensor([[5, 6, 7, 8]])

print('Elementwise sum:')
print(x + y)
print(torch.add(x, y))
print(x.add(y))

# Elementwise difference
print('\nElementwise difference:')
print(x - y)
print(torch.sub(x, y))
print(x.sub(y))

# Elementwise product
print('\nElementwise product:')
print(x * y)
print(torch.mul(x, y))
print(x.mul(y))

# Elementwise division
print('\nElementwise division')
print(x / y)
print(torch.div(x, y))
print(x.div(y))

# Elementwise power
print('\nElementwise power')
print(x ** y)
print(torch.pow(x, y))
print(x.pow(y))

Here some basic matrix operations are showed, such as transopse, matrix product, inverse etc. Floor function is also given. 

In [8]:
x = torch.rand((3,3))

print(x), x.shape
#scale first 


print(2*x)
print(2+x)
print(torch.ceil(x))
print(torch.t(x))

y=torch.eye(3)
z=torch.zeros(3,3)

print(torch.mm(x,z))
print(x@y)

t=torch.inverse(x)
print(t)
print(t@x)
#M+mat1/*/mat2
M = torch.randn(2, 3)
mat1 = torch.randn(2, 3)
mat2 = torch.randn(3, 3)
torch.addmm(M, mat1, mat2)

tensor([[0.0247, 0.3489, 0.8341],
        [0.0135, 0.5318, 0.3790],
        [0.0652, 0.0941, 0.0437]])
tensor([[0.0495, 0.6978, 1.6681],
        [0.0271, 1.0635, 0.7580],
        [0.1304, 0.1881, 0.0873]])
tensor([[2.0247, 2.3489, 2.8341],
        [2.0135, 2.5318, 2.3790],
        [2.0652, 2.0941, 2.0437]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[0.0247, 0.0135, 0.0652],
        [0.3489, 0.5318, 0.0941],
        [0.8341, 0.3790, 0.0437]])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[0.0247, 0.3489, 0.8341],
        [0.0135, 0.5318, 0.3790],
        [0.0652, 0.0941, 0.0437]])
tensor([[ 0.6292, -3.2003, 15.7605],
        [-1.2212,  2.6989, -0.0969],
        [ 1.6912, -1.0340, -0.4271]])
tensor([[ 1.0000e+00, -1.5333e-07,  2.0123e-09],
        [ 4.5493e-09,  1.0000e+00, -1.1170e-07],
        [-2.4510e-09, -2.8327e-08,  1.0000e+00]])


tensor([[ 0.3153, -1.1431, -1.3456],
        [ 0.4520,  0.6048,  2.8871]])

Outer product

In [41]:
v1 = torch.arange(1, 4)    # Size 3
v2 = torch.arange(1, 3)    # Size 2
r = torch.ger(v1, v2)
print(v1)
print(v2)
print(r)

tensor([1, 2, 3])
tensor([1, 2])
tensor([[1, 2],
        [2, 4],
        [3, 6]])


# Generate distribution
Here are some examples about generating numbers from different distributions. Cases of uniform, normal, bernoulli are given.

In [66]:
u = torch.Tensor(2, 2).uniform_(0, 1)
print(u)

b = torch.bernoulli(u)  
print(b)

torch.normal(mean=torch.arange(1., 11.), std=torch.arange(1, 0, -0.1))

tensor([[0.5309, 1.0000],
        [0.3665, 0.3712]])
tensor([[0., 1.],
        [0., 1.]])


tensor([ 1.1094,  0.4364,  2.9542,  3.8790,  5.0204,  6.2232,  6.9276,  7.7095,
         8.5552, 10.1018])

# Running on a GPU

In [ ]:
import torch 
print(torch.__version__)

print(torch.cuda.current_device())
print(torch.cuda.device(0))
print(torch.cuda.device_count())
print(torch.cuda.get_device_name(0))
print(torch.cuda.is_available())
print(torch.cuda.current_device())

In [1]:
import time
import torch

a_cpu = torch.randn(100, 100, dtype=torch.float32)
b_cpu = torch.randn(100, 100, dtype=torch.float32)

a_gpu = a_cpu.cuda()
b_gpu = b_cpu.cuda()
torch.cuda.synchronize()

t0 = time.time()
c_cpu = a_cpu + b_cpu
t1 = time.time()
c_gpu = a_gpu + b_gpu
torch.cuda.synchronize()
t2 = time.time()

# Check that they computed the same thing
diff = (c_gpu.cpu() - c_cpu).abs().max().item()
print('Max difference between c_gpu and c_cpu:', diff)

cpu_time = 1000.0 * (t1 - t0)
gpu_time = 1000.0 * (t2 - t1)
print('CPU time: %.2f ms' % cpu_time)
print('GPU time: %.2f ms' % gpu_time)
print('GPU speedup: %.2f x' % (cpu_time / gpu_time))

RuntimeError: ignored